[package]
name = "dns"
version = "0.1.0"
authors = ["Tyler Stanish <tystanish@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
resize-slice = "0.1.3"
